<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RestorePackagesPath>$(UserProfile)\.nuget\packages</RestorePackagesPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="WixToolset.UI.wixext" Version="6.0.2" />
    <PackageReference Include="WixToolset.Bal.wixext" Version="6.0.2" />
  </ItemGroup>
</Project>
